### ISSUE TITLE
allow lowercase code

### ISSUE THREAD

**Issue by Rubyer77** [riccione/hermes#1]
`hermes add -a hello -c xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` is invalid

`hermes add -a hello -c XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` is valid

**Comment by riccione** [comment]
Thanks. I will look into it!

**Comment by riccione** [comment]
I fixed this issue 2e5ea37bc1ba3e3e2ae6a8795e7472d7aa7a3d99
